# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_CaeFemElemC')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_CaeFemElemC')
    _CaeFemElemC = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_CaeFemElemC', [dirname(__file__)])
        except ImportError:
            import _CaeFemElemC
            return _CaeFemElemC
        try:
            _mod = imp.load_module('_CaeFemElemC', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _CaeFemElemC = swig_import_helper()
    del swig_import_helper
else:
    import _CaeFemElemC
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def CPS4FormBC(X0: 'double', Y0: 'double', X1: 'double', Y1: 'double', X2: 'double', Y2: 'double', X3: 'double', Y3: 'double', r: 'double', s: 'double', t: 'double', BC: 'double *', det_: 'double *') -> "int":
    return _CaeFemElemC.CPS4FormBC(X0, Y0, X1, Y1, X2, Y2, X3, Y3, r, s, t, BC, det_)
CPS4FormBC = _CaeFemElemC.CPS4FormBC

def SH4BasicsC(r: 'double', s: 'double', t: 'double', N: 'double *', br: 'double *', bs: 'double *', JJ: 'double *', JI: 'double *', vv: 'double *', XX: 'double *', a: 'double *', Vn: 'double *', EdgeDir: 'double *') -> "int":
    return _CaeFemElemC.SH4BasicsC(r, s, t, N, br, bs, JJ, JI, vv, XX, a, Vn, EdgeDir)
SH4BasicsC = _CaeFemElemC.SH4BasicsC

def SH4FormBC(r: 'double', s: 'double', t: 'double', BB: 'double *', Data: 'double *', XX: 'double *', a: 'double *', Vn: 'double *', EdgeDir: 'double *', gg0: 'double *', gg1: 'double *', TD: 'double *') -> "int":
    return _CaeFemElemC.SH4FormBC(r, s, t, BB, Data, XX, a, Vn, EdgeDir, gg0, gg1, TD)
SH4FormBC = _CaeFemElemC.SH4FormBC

def SH4FormGeomC(r: 'double', s: 'double', t: 'double', GeomK: 'double *', Data: 'double *', sig: 'double *', gg0: 'double *', gg1: 'double *') -> "int":
    return _CaeFemElemC.SH4FormGeomC(r, s, t, GeomK, Data, sig, gg0, gg1)
SH4FormGeomC = _CaeFemElemC.SH4FormGeomC
# This file is compatible with both classic and new-style classes.


