# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_ConFemMatC')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_ConFemMatC')
    _ConFemMatC = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ConFemMatC', [dirname(__file__)])
        except ImportError:
            import _ConFemMatC
            return _ConFemMatC
        try:
            _mod = imp.load_module('_ConFemMatC', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _ConFemMatC = swig_import_helper()
    del swig_import_helper
else:
    import _ConFemMatC
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def PrinCLT_1(vx: 'double', vy: 'double', vxy: 'double', pEps: 'double *') -> "void":
    return _ConFemMatC.PrinCLT_1(vx, vy, vxy, pEps)
PrinCLT_1 = _ConFemMatC.PrinCLT_1

def PrinCLT_2(vx: 'double', vy: 'double', vxy: 'double') -> "double":
    return _ConFemMatC.PrinCLT_2(vx, vy, vxy)
PrinCLT_2 = _ConFemMatC.PrinCLT_2

def State4C_(Emod: 'double', nu: 'double', kap: 'double', delt: 'double', sigEta1_4: 'double', ww1_4: 'double', MatML: 'double [][3]', epsL: 'double *', sigL: 'double *', ElemStateVarN: 'double *', ww: 'double *') -> "int":
    return _ConFemMatC.State4C_(Emod, nu, kap, delt, sigEta1_4, ww1_4, MatML, epsL, sigL, ElemStateVarN, ww)
State4C_ = _ConFemMatC.State4C_

def State1C_(i: 'int', D1: 'double', Emod: 'double', nu: 'double', aect: 'double', eta_: 'double', delt: 'double', xi: 'double', fct: 'double', alfa: 'double', epsct_: 'double', sigEta1_1: 'double', ww1_1: 'double', MatML: 'double [][3]', epsL: 'double *', sigL: 'double *', ElemStateVarN: 'double *', ww: 'double *') -> "int":
    return _ConFemMatC.State1C_(i, D1, Emod, nu, aect, eta_, delt, xi, fct, alfa, epsct_, sigEta1_1, ww1_1, MatML, epsL, sigL, ElemStateVarN, ww)
State1C_ = _ConFemMatC.State1C_

def State2C_(D2_1: 'double', Emod: 'double', nu: 'double', eta_2: 'double', beta1: 'double', delt: 'double', xi: 'double', sigEta1_2: 'double', ww1_2: 'double', MatML: 'double [][3]', epsL: 'double *', sigL: 'double *', ww: 'double *') -> "int":
    return _ConFemMatC.State2C_(D2_1, Emod, nu, eta_2, beta1, delt, xi, sigEta1_2, ww1_2, MatML, epsL, sigL, ww)
State2C_ = _ConFemMatC.State2C_

def State3C_(Emod: 'double', nu: 'double', MatML: 'double [][3]', epsL: 'double *', sigL: 'double *', ww: 'double *') -> "int":
    return _ConFemMatC.State3C_(Emod, nu, MatML, epsL, sigL, ww)
State3C_ = _ConFemMatC.State3C_

def state4C2_(ww2_4: 'double', MatML: 'double [][3]', sigL: 'double *', ElemStateVarN: 'double *', ww: 'double *') -> "int":
    return _ConFemMatC.state4C2_(ww2_4, MatML, sigL, ElemStateVarN, ww)
state4C2_ = _ConFemMatC.state4C2_

def State1C2_(D1: 'double', Emod: 'double', aect: 'double', eta_: 'double', fct: 'double', alfa: 'double', sigEta2_1: 'double', ww2_1: 'double', MatML: 'double [][3]', epsL: 'double *', sigL: 'double *', ElemStateVarN: 'double *', ww: 'double *') -> "int":
    return _ConFemMatC.State1C2_(D1, Emod, aect, eta_, fct, alfa, sigEta2_1, ww2_1, MatML, epsL, sigL, ElemStateVarN, ww)
State1C2_ = _ConFemMatC.State1C2_

def State2C2_(nu: 'double', D2_2: 'double', eta_2: 'double', beta2: 'double', sigEta2_2: 'double', ww2_2: 'double', MatML: 'double [][3]', epsL: 'double *', sigL: 'double *', ww: 'double *') -> "int":
    return _ConFemMatC.State2C2_(nu, D2_2, eta_2, beta2, sigEta2_2, ww2_2, MatML, epsL, sigL, ww)
State2C2_ = _ConFemMatC.State2C2_

def State3C2_(Emod: 'double', MatML: 'double [][3]', epsL: 'double *', sigL: 'double *', ww: 'double *') -> "int":
    return _ConFemMatC.State3C2_(Emod, MatML, epsL, sigL, ww)
State3C2_ = _ConFemMatC.State3C2_

def ElasticLTC1(ElemDim: 'int', ElemPlSt: 'bool', ElemLch: 'double', ElemStateVar: 'double *', ElemStateVarN: 'double *', ElemDataP: 'double *', selfEmod: 'double', selfnu: 'double', selfEpsct: 'double', selfwcr: 'double', selfbw: 'double', selfCrackVisc: 'double', selffct: 'double', Eps: 'double *', sig: 'double *', MatM: 'double *', ww: 'double *') -> "int":
    return _ConFemMatC.ElasticLTC1(ElemDim, ElemPlSt, ElemLch, ElemStateVar, ElemStateVarN, ElemDataP, selfEmod, selfnu, selfEpsct, selfwcr, selfbw, selfCrackVisc, selffct, Eps, sig, MatM, ww)
ElasticLTC1 = _ConFemMatC.ElasticLTC1

def eighC(I1: 'double', J2: 'double', Eps: 'double *', la: 'double *', vv: 'double *') -> "int":
    return _ConFemMatC.eighC(I1, J2, Eps, la, vv)
eighC = _ConFemMatC.eighC

def EquivStrain1C(I1: 'double', J2: 'double', J2S: 'double', Eps: 'double *', EpsD: 'double *', kap_: 'double *', nd: 'double *', Hd: 'double *', cc0: 'double', cc1: 'double', cc2: 'double', cc3: 'double', LaMax: 'double *', eVec: 'double *', data: 'double *') -> "int":
    return _ConFemMatC.EquivStrain1C(I1, J2, J2S, Eps, EpsD, kap_, nd, Hd, cc0, cc1, cc2, cc3, LaMax, eVec, data)
EquivStrain1C = _ConFemMatC.EquivStrain1C

def eighC2(I1: 'double', J2D: 'double', Eps: 'double *', la: 'double *', vv: 'double *') -> "int":
    return _ConFemMatC.eighC2(I1, J2D, Eps, la, vv)
eighC2 = _ConFemMatC.eighC2

def eigJacobiSym(Eps: 'double *', la: 'double *', vv: 'double *') -> "int":
    return _ConFemMatC.eigJacobiSym(Eps, la, vv)
eigJacobiSym = _ConFemMatC.eigJacobiSym

def ViscExten3DC1(Dt: 'double', eta: 'double', Dps: 'double *', ElemStateVar: 'double *', ElemStateVarN: 'double *', sI: 'int', Veps: 'double *') -> "double":
    return _ConFemMatC.ViscExten3DC1(Dt, eta, Dps, ElemStateVar, ElemStateVarN, sI, Veps)
ViscExten3DC1 = _ConFemMatC.ViscExten3DC1

def eigJacobiSymWrapper(Eps: 'double *', la: 'double *', vv: 'double *') -> "int":
    return _ConFemMatC.eigJacobiSymWrapper(Eps, la, vv)
eigJacobiSymWrapper = _ConFemMatC.eigJacobiSymWrapper

def IsoDamC1(ElemDim: 'int', ElemPlSt: 'bool', PrinStrains: 'bool', ElemLch: 'double', ElemStateVar: 'double *', ElemStateVarN: 'double *', Eps: 'double *', sig: 'double *', MatM: 'double *', LiTy: 'int', cc0: 'double', cc1: 'double', cc2: 'double', cc3: 'double', RType: 'int', EpsR: 'double *', kapStrength: 'double', ElemCrBws: 'double', gam2: 'double', kapUlt: 'double', edt: 'double', ed: 'double', gd: 'double', nu: 'double', Emod: 'double', Dps: 'double *', eta: 'double', RegPar: 'double', sigR: 'double *', CR: 'double *', Dt: 'double', sVsTol: 'double', DataOut: 'double *') -> "int":
    return _ConFemMatC.IsoDamC1(ElemDim, ElemPlSt, PrinStrains, ElemLch, ElemStateVar, ElemStateVarN, Eps, sig, MatM, LiTy, cc0, cc1, cc2, cc3, RType, EpsR, kapStrength, ElemCrBws, gam2, kapUlt, edt, ed, gd, nu, Emod, Dps, eta, RegPar, sigR, CR, Dt, sVsTol, DataOut)
IsoDamC1 = _ConFemMatC.IsoDamC1

def IsoDamUniaxC1(ElemDim: 'int', ElemPlSt: 'bool', ElemLch: 'double', ElemStateVar: 'double *', ElemStateVarN: 'double *', Eps: 'double *', sig: 'double *', MatM: 'double *', LiTy: 'int', alpha: 'double', cc1: 'double', cc2: 'double', cc3: 'double', RType: 'int', EpsR: 'double *', kapStrength: 'double', ElemCrBws: 'double', gam2: 'double', kapUlt: 'double', edt: 'double', ed: 'double', gd: 'double', nu: 'double', Emod: 'double', Dps: 'double *', eta: 'double', RegPar: 'double', sigR: 'double *', CR: 'double *', Dt: 'double', sVsTol: 'double', DataOut: 'double *') -> "int":
    return _ConFemMatC.IsoDamUniaxC1(ElemDim, ElemPlSt, ElemLch, ElemStateVar, ElemStateVarN, Eps, sig, MatM, LiTy, alpha, cc1, cc2, cc3, RType, EpsR, kapStrength, ElemCrBws, gam2, kapUlt, edt, ed, gd, nu, Emod, Dps, eta, RegPar, sigR, CR, Dt, sVsTol, DataOut)
IsoDamUniaxC1 = _ConFemMatC.IsoDamUniaxC1

def Rankine(PrinStrains: 'bool', ElemDim: 'int', Eps_: 'double *', sig0: 'double *', eVec: 'double *', laMax: 'double *') -> "int":
    return _ConFemMatC.Rankine(PrinStrains, ElemDim, Eps_, sig0, eVec, laMax)
Rankine = _ConFemMatC.Rankine

def RankineUpd(sig0: 'double *', eVec: 'double *', ElemStateVarN: 'double *', laMax: 'double *', off: 'int') -> "int":
    return _ConFemMatC.RankineUpd(sig0, eVec, ElemStateVarN, laMax, off)
RankineUpd = _ConFemMatC.RankineUpd

def ElasticLTC2(ElemDim: 'int', ElemPlSt: 'bool', PrinStrains: 'bool', ElemStateVar: 'double *', ElemStateVarN: 'double *', Eps: 'double *', sig: 'double *', MatM: 'double *', nu: 'double', Emod: 'double', Dps: 'double *', eta: 'double', Dt: 'double', DataOut: 'double *') -> "int":
    return _ConFemMatC.ElasticLTC2(ElemDim, ElemPlSt, PrinStrains, ElemStateVar, ElemStateVarN, Eps, sig, MatM, nu, Emod, Dps, eta, Dt, DataOut)
ElasticLTC2 = _ConFemMatC.ElasticLTC2

def DamFunc1(kap0V: 'double', alphaV: 'double', betaV: 'double', kapOld: 'double', eta: 'double', kap: 'double *', dd: 'double *', Dp: 'double *') -> "void":
    return _ConFemMatC.DamFunc1(kap0V, alphaV, betaV, kapOld, eta, kap, dd, Dp)
DamFunc1 = _ConFemMatC.DamFunc1

def DevStiffness(m00: 'double', m01: 'double', m02: 'double', m11: 'double', m12: 'double', m22: 'double', n02: 'double', n12: 'double', n22: 'double', tbt: 'double', tbt2: 'double', obt: 'double', obt2: 'double', nn: 'double *', DVD: 'double *') -> "void":
    return _ConFemMatC.DevStiffness(m00, m01, m02, m11, m12, m22, n02, n12, n22, tbt, tbt2, obt, obt2, nn, DVD)
DevStiffness = _ConFemMatC.DevStiffness

def MicroPlaneC1(ElemDim: 'int', ElemPlSt: 'bool', PrinStrains: 'bool', ElemLch: 'double', ElemStateVar: 'double *', ElemStateVarN: 'double *', Eps: 'double *', sig: 'double *', MatM: 'double *', type: 'int', E_V: 'double', E_DM: 'double', KV0: 'double', kV1: 'double', kV2: 'double', kap0V: 'double', alphaV: 'double', betaV: 'double', RType: 'int', ElemCrBws: 'double', gam2: 'double', kapUlt: 'double', eps_ct: 'double', e0: 'double', ed: 'double', gd: 'double', nu: 'double', Emod: 'double', Dps: 'double *', etaV: 'double', Dt: 'double', sVsTol: 'double', DataOut: 'double *', nState: 'int', nInt: 'int', PlStressI: 'int', PlStressL: 'double', iS: 'int') -> "int":
    return _ConFemMatC.MicroPlaneC1(ElemDim, ElemPlSt, PrinStrains, ElemLch, ElemStateVar, ElemStateVarN, Eps, sig, MatM, type, E_V, E_DM, KV0, kV1, kV2, kap0V, alphaV, betaV, RType, ElemCrBws, gam2, kapUlt, eps_ct, e0, ed, gd, nu, Emod, Dps, etaV, Dt, sVsTol, DataOut, nState, nInt, PlStressI, PlStressL, iS)
MicroPlaneC1 = _ConFemMatC.MicroPlaneC1
# This file is compatible with both classic and new-style classes.


