# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_LinAlg2')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_LinAlg2')
    _LinAlg2 = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_LinAlg2', [dirname(__file__)])
        except ImportError:
            import _LinAlg2
            return _LinAlg2
        try:
            _mod = imp.load_module('_LinAlg2', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _LinAlg2 = swig_import_helper()
    del swig_import_helper
else:
    import _LinAlg2
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def sim0_so(r: 'double *', a: 'double *', b: 'double *', b1: 'long long *', b2: 'int *', n: 'int') -> "void":
    return _LinAlg2.sim0_so(r, a, b, b1, b2, n)
sim0_so = _LinAlg2.sim0_so

def sim0_lu(a: 'double *', b: 'double *', b1: 'long long *', b2: 'int *', n: 'int') -> "void":
    return _LinAlg2.sim0_lu(a, b, b1, b2, n)
sim0_lu = _LinAlg2.sim0_lu

def sim0_mmul(le: 'double *', a: 'double *', b: 'double *', ri: 'double *', b1: 'long long *', b2: 'int *', n: 'int') -> "void":
    return _LinAlg2.sim0_mmul(le, a, b, ri, b1, b2, n)
sim0_mmul = _LinAlg2.sim0_mmul

def sim1_so(r: 'double *', a: 'double *', b1: 'long long *', b2: 'int *', n: 'int') -> "void":
    return _LinAlg2.sim1_so(r, a, b1, b2, n)
sim1_so = _LinAlg2.sim1_so

def sim1_lu(a: 'double *', b1: 'long long *', b2: 'int *', n: 'int') -> "void":
    return _LinAlg2.sim1_lu(a, b1, b2, n)
sim1_lu = _LinAlg2.sim1_lu

def sim1_mmul(le: 'double *', a: 'double *', ri: 'double *', b1: 'long long *', b2: 'int *', n: 'int') -> "void":
    return _LinAlg2.sim1_mmul(le, a, ri, b1, b2, n)
sim1_mmul = _LinAlg2.sim1_mmul

def sim1_luP(a: 'double *', b1: 'long long *', b2: 'int *', n: 'int', NK: 'int') -> "void":
    return _LinAlg2.sim1_luP(a, b1, b2, n, NK)
sim1_luP = _LinAlg2.sim1_luP

def BoundFinishLC(N: 'int', k: 'int', SDiag: 'long long *', Skyline: 'int *', KVecU: 'double *', SymSys: 'int', KVecL: 'double *') -> "void":
    return _LinAlg2.BoundFinishLC(N, k, SDiag, Skyline, KVecU, SymSys, KVecL)
BoundFinishLC = _LinAlg2.BoundFinishLC

def RightHandSideLC(N: 'int', k: 'int', LF: 'double', LT: 'double', ub: 'double *', uub: 'double *', SDiag: 'long long *', Skyline: 'int *', pp: 'double *', pp0: 'double *', KVecU: 'double *', SymSys: 'int', KVecL: 'double *') -> "void":
    return _LinAlg2.RightHandSideLC(N, k, LF, LT, ub, uub, SDiag, Skyline, pp, pp0, KVecU, SymSys, KVecL)
RightHandSideLC = _LinAlg2.RightHandSideLC

def RightHandSideLC_(N: 'int', k: 'int', SDiag: 'long long *', Skyline: 'int *', pp: 'double *', pp0: 'double *', KVecU: 'double *', SymSys: 'int', KVecL: 'double *', val: 'double', valT: 'double') -> "void":
    return _LinAlg2.RightHandSideLC_(N, k, SDiag, Skyline, pp, pp0, KVecU, SymSys, KVecL, val, valT)
RightHandSideLC_ = _LinAlg2.RightHandSideLC_
# This file is compatible with both classic and new-style classes.


